Re-populate the search query input box
jenkinsci/data-tables-api-plugin pull request #332
Opened 2023-02-20 21:57 UTC by mPokornyETM

The search box is a very important part of the UI. 
However when there is a need to refresh the page, it's cumbersome to have to re-enter the search query after every action.

The search query should be automatically re-populated after an page reload.

To enable / disable this scenario might be the table-attribute 'remember-search-text' used.
like
```
 <div class="table-responsive">
    <table class="jenkins-table jenkins-!-margin-bottom-4 data-table"
           id="lockable-resources"
          isLoaded="true"
          remember-search-text="true"
          data-columns-definition="[null, null, null, null, null]"
          data-table-configuration="{}">
      <colgroup>
...
```

Per default it is set to false, that means disabled, therefore it shall has no side effects in plugins currently used this API.

We need this feature to fix this [issue](https://github.com/jenkinsci/lockable-resources-plugin/issues/461)

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- ~~[ ] Link to relevant pull requests, esp. upstream and downstream changes~~
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2023-02-20 21:59 UTC, mPokornyETM commented
I hope it is filled correctly, It is my first PR in this repo ;-)

2023-02-26 15:37 UTC, uhafner requested changes
Otherwise it looks fine!

2023-02-26 15:37 UTC, uhafner commented on src/main/webapp/js/table.js
> +            if (table.attr('remember-search-text') === 'true') {
Please use `data-remember-search-text` so it is consistent with the rest of the properties.

2023-02-26 15:38 UTC, uhafner commented
It would be helpful if you can describe the new property in the README as well.

2023-02-27 10:37 UTC, mPokornyETM commented on src/main/webapp/js/table.js
> +            if (table.attr('remember-search-text') === 'true') {
Sure.  I'll do it. Currently I am sick it might take a while.

2023-02-28 14:00 UTC, mPokornyETM commented
> I wonder if I should remove my state saving code totally and try to use the native https://datatables.net/reference/option/stateSave option?

I tries that, but it has not works for me. And I have no idea why. But yes it will be fine.

2023-03-03 15:33 UTC, mPokornyETM commented on src/main/webapp/js/table.js
> +            if (table.attr('remember-search-text') === 'true') {
changed

2023-03-03 15:34 UTC, mPokornyETM commented
> It would be helpful if you can describe the new property in the README as well.

added. I hope it enough so. Because I didn't find better place.

2023-03-11 11:33 UTC, uhafner commented
> > I wonder if I should remove my state saving code totally and try to use the native https://datatables.net/reference/option/stateSave option?
> 
> I tries that, but it has not works for me. And I have no idea why. But yes it will be fine.

I also tried without success. Either a bug in Datatables, or some interferences with our Jenkins frameworks.

2023-03-11 11:36 UTC, uhafner approved these changes

2023-03-11 11:36 UTC, merged